### register
POST http://localhost:8080/api/register
content-type: application/json

{
    "name": "test",
    "email": "test@example.com",
    "password": "1234"
}

### login
POST http://localhost:8080/api/login
content-type: application/json

{
    "email": "test@example.com",
    "password": "1234"
}

### get all surveys
GET http://localhost:8080/api/survey

### get single survey
GET http://localhost:8080/api/survey/id

### create survey
POST http://localhost:8080/api/survey
content-type: "application/json"

{
    "name": "survey-1",
    "description": "lorem ipsum"
}

