POST http://localhost:8080/api/register
content-type: application/json

{
    "name": "test",
    "email": "test@example.com",
    "password": "1234"
}

###

POST http://localhost:8080/api/login
content-type: application/json

{
    "email": "test@example.com",
    "password": "1234"
}